name: finance_management
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.2
  go_router: ^15.1.2
  hive: ^2.2.3
  flutter_svg: ^2.0.10
  url_launcher: ^6.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/IconComponents/
      - assets/FunctionalIcon/
      - assets/IconComponents/
      - assets/BottomNavigationIcon/
    #assets:
